# Generated by Django 3.0.8 on 2020-08-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('carousel_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('carousel_url', models.CharField(max_length=100)),
                ('redirect_url', models.CharField(max_length=100)),
                ('carousel_rand', models.IntegerField()),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_carousel',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('category_level', models.IntegerField()),
                ('parent_id', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('category_rank', models.IntegerField()),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100)),
                ('goods_intro', models.CharField(max_length=100)),
                ('goods_category', models.CharField(max_length=100)),
                ('goods_cover_img', models.CharField(max_length=100)),
                ('goods_carousel', models.CharField(max_length=100)),
                ('goods_detail_content', models.CharField(max_length=100)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('stock_num', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('goods_sell_status', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goods_info',
            },
        ),
        migrations.CreateModel(
            name='Mall_order',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('total_price', models.FloatField()),
                ('pay_status', models.IntegerField(default=0)),
                ('pay_type', models.CharField(max_length=100)),
                ('pay_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.IntegerField(default=0)),
                ('extra_info', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mall_order',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('login_name', models.CharField(max_length=100)),
                ('user_pwd', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('locked', models.IntegerField(default=0)),
                ('introduce', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_user',
            },
        ),
        migrations.CreateModel(
            name='User_collection',
            fields=[
                ('collection_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('is_deleted', models.IntegerField(default=0)),
                ('mall_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Mall_order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User')),
            ],
            options={
                'db_table': 'user_collection',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('Token_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('update_time', models.DateField(auto_now_add=True)),
                ('expire_time', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('order_item_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100)),
                ('goods_cover_img', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('goods_count', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Goods')),
                ('mall_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Mall_order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Order_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_phone', models.CharField(max_length=32)),
                ('province_name', models.CharField(max_length=32)),
                ('city_name', models.CharField(max_length=32)),
                ('region_name', models.CharField(max_length=32)),
                ('detail_address', models.CharField(max_length=100)),
                ('mall_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Mall_order')),
            ],
            options={
                'db_table': 'order_address',
            },
        ),
        migrations.AddField(
            model_name='mall_order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_item_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goods_count', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User')),
            ],
            options={
                'db_table': 'shopping_cart',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_phone', models.IntegerField()),
                ('default_flag', models.IntegerField(default=0)),
                ('province_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
