# Generated by Django 3.0.8 on 2020-08-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_goods_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mall_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order_address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order_address',
            name='mall_order',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='order_item',
            name='mall_order',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_collection',
            name='mall_order',
        ),
        migrations.RemoveField(
            model_name='user_collection',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='is_collection',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mall_order',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_address',
            name='order_id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='goods_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_item',
            name='order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_collection',
            name='order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_collection',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
